[package]
name = "subspace-core-rust"
version = "0.1.0"
authors = ["jwagstaff"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3.2"
rand = "0.7.2"
ring = "0.16.9"
rug = "1.9.0"

[[bench]]
name = "sloth"
harness = false