name: Rust

on:
  push:
    branches: [ updates ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Rust Nightly
        run: |
          rustup toolchain install nightly
          rustup default nightly
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
