name: Rust

on:
  release:
    types: [ published ]
  push:
    branches: [ updates ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Rust Nightly
        run: |
          rustup toolchain install nightly
          rustup default nightly
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  # TODO: We probably want to do this for releases in the future
  build-container-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.GITHUB_REF_SLUG }}
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            ghcr.io/subspace/subspace:${{ env.GITHUB_REF_SLUG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Push container image
        run: |
          docker push ghcr.io/subspace/subspace:${{ env.GITHUB_REF_SLUG }}
